language: generic
sudo: required

services: 
    - docker

before_install:
    - docker build -t 23david73/docker-react-test -f Dockerfile.dev . 

script:
    - docker run -e CI=true 23david73/docker-react-test npm run test

deploy: 
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react-test"
    env: "DockerReactTest-env-1"
    bucket_name: "elasticbeanstalk-us-east-2-816219623859"
    bucket_path: "docker-react-test"
    on: 
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: "$AWS_SECRET_KEY"